# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07be6ff23adb658f5dfc6135f935348a7faeb0f67089cba34823b06e03bcf5f4fa1c0788ab2084b98f25372fdb1fcd94e23bca6a33988ac180278c8f0cafab21

test:
  secret_key_base: 11fd7f461557066ac99e50354d4d8f14639b0b337fda889c7019b1671bf6a60a51830f93dd5d48e8e8ab6a4959fb223b54a52205592f2e83ad3ce45565ea5ee1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
